version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=postgresql://expense_user:expense_pass@db:5432/expense_tracker
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=expense_tracker
      - POSTGRES_USER=expense_user
      - POSTGRES_PASSWORD=expense_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker -l info
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=postgresql://expense_user:expense_pass@db:5432/expense_tracker
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A config beat -l info
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=postgresql://expense_user:expense_pass@db:5432/expense_tracker
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
